# from https://www.drupal.org/requirements/php#drupalversions
FROM php:7.0-apache

RUN a2enmod rewrite

# Required to disable a bening apache error.
RUN { \
		echo "ServerName localhost" > /etc/apache2/conf-available/fqdn.conf; \
		a2enconf fqdn; \
	}

# install the PHP extensions we need
RUN apt-get update && apt-get install -y libpng12-dev libjpeg-dev libpq-dev mysql-client \
	&& rm -rf /var/lib/apt/lists/* \
	&& docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
	&& docker-php-ext-install gd mbstring opcache pdo pdo_mysql pdo_pgsql zip
  
# set recommended PHP.ini settings
# see https://secure.php.net/manual/en/opcache.installation.php
RUN { \
		echo 'opcache.memory_consumption=128'; \
		echo 'opcache.interned_strings_buffer=8'; \
		echo 'opcache.max_accelerated_files=4000'; \
		echo 'opcache.revalidate_freq=60'; \
		echo 'opcache.fast_shutdown=1'; \
		echo 'opcache.enable_cli=1'; \
	} > /usr/local/etc/php/conf.d/opcache-recommended.ini

WORKDIR /var/www/html

# install Drush
RUN { \
		php -r "readfile('https://s3.amazonaws.com/files.drush.org/drush.phar');" > drush; \
		chmod +x drush; \
		mv drush /usr/local/bin; \
	}
  
# copy code over and set permissions
COPY . .
RUN { \
		chmod +x deployment/*.sh; \
	}

# Create files directory with the right permissions
RUN { \
		mkdir ./sites/default/files; \
    chmod a+w ./sites/default/files; \
	}
  
RUN chown -R www-data:www-data sites modules themes
