#!/bin/bash -x

# secrets are expected to be passed as parameters as they are not populated in the environment variables.

azure webapp config appsettings delete -g $RESOURCEGROUP -n $BUILD_DEFINITIONNAME -a "DOCKER_CUSTOM_IMAGE_NAME,DOCKER_REGISTRY_SERVER_URL,DOCKER_REGISTRY_SERVER_USERNAME,DOCKER_REGISTRY_SERVER_PASSWORD,DBNAME,DBUSERNAME,DBPASSWORD,DBHOST"
 
azure webapp config appsettings set -g $RESOURCEGROUP -n $BUILD_DEFINITIONNAME -a "\
  DOCKER_CUSTOM_IMAGE_NAME=$DOCKERREGISTRY_SERVER/$BUILD_DEFINITIONNAME:$BUILD_BUILDID,\
  DOCKER_REGISTRY_SERVER_URL=http://$DOCKERREGISTRY_SERVER,\
  DOCKER_REGISTRY_SERVER_USERNAME=$DOCKER_REGISTRY_SERVER_USERNAME,\
  DOCKER_REGISTRY_SERVER_PASSWORD=$1,\
  DBNAME=${BUILD_DEFINITIONNAME}_${RELEASE_ENVIRONMENTNAME},\
  DBUSERNAME=$DBUSERNAME,\
  DBPASSWORD=$2,\
  DBHOST=$DBHOST\
  "
